<?php

/**
 * Proves the PHP port produces exactly what the Python did.
 *
 *     php tests/compare_with_python.php
 *
 * tests/golden_vectors.json was generated by running the original
 * backend/pre_quiz.py and backend/adaptive_test.py over a fixed set of
 * inputs and recording every output. This replays the same inputs through
 * the PHP and compares, value for value.
 *
 * Why bother: a port that is subtly wrong is worse than no port. A seed off
 * by one, or a midpoint rounded differently, produces a plausible-looking
 * profile that quietly recommends the wrong earphones — and nothing
 * anywhere would report an error. Only a comparison catches that.
 *
 * Every A/B pattern here is deterministic, so the comparison is exact
 * rather than approximate. Floating point is compared with a tolerance of
 * 1e-9, which is far tighter than the 0.1 dB the values are rounded to.
 */

if (PHP_SAPI !== "cli") {
    http_response_code(404);
    exit;
}

require_once __DIR__ . "/../api/pre_quiz.php";

// The adaptive test keeps its state in $_SESSION. There is no session in
// CLI, but the code only ever reads and writes one key, so a plain array
// stands in perfectly.
$_SESSION = [];
require_once __DIR__ . "/../api/adaptive_test.php";

const TOLERANCE = 1e-9;

$goldenPath = __DIR__ . "/golden_vectors.json";
if (!file_exists($goldenPath)) {
    fwrite(STDERR, "Missing {$goldenPath}\n");
    exit(1);
}
$golden = json_decode(file_get_contents($goldenPath), true);

$failures = 0;
$checks = 0;

function same($a, $b) {
    if (is_float($a) || is_float($b)) {
        return abs((float)$a - (float)$b) <= TOLERANCE;
    }
    return $a == $b;
}

function check($label, $got, $want) {
    global $failures, $checks;
    $checks++;
    if (same($got, $want)) {
        return true;
    }
    $failures++;
    printf("  FAIL  %s\n        got  %s\n        want %s\n",
        $label, json_encode($got), json_encode($want));
    return false;
}

function checkMap($label, $got, $want) {
    $got = (array)$got;
    $want = (array)$want;
    $ok = true;
    foreach ($want as $key => $value) {
        $ok = check("{$label}[{$key}]", $got[$key] ?? null, $value) && $ok;
    }
    return $ok;
}


/* ─────────────────────────────── the pre-quiz ─────────────────────────── */

echo "\nPre-quiz seeds\n";

foreach ($golden["quiz"] as $name => $expected) {
    $answers = [
        "empty" => [],
        "all_warm" => ["genre"=>"hiphop","signature"=>"warm","vocals"=>"forward",
                       "harshness"=>"often","punch"=>"often","environment"=>"noisy"],
        "all_bright" => ["genre"=>"classical","signature"=>"bright","vocals"=>"laidback",
                         "harshness"=>"never","punch"=>"never","environment"=>"quiet"],
        "vshape" => ["genre"=>"rock","signature"=>"vshape","vocals"=>"natural",
                     "harshness"=>"sometimes","punch"=>"sometimes","environment"=>"mixed"],
        "partial" => ["genre"=>"pop","signature"=>"balanced"],
        "unknown_keys" => ["genre"=>"NOPE","bogus"=>"x","signature"=>"warm"],
        "clamped" => ["genre"=>"hiphop","signature"=>"warm","punch"=>"often"],
    ][$name];

    $got = quiz_score_answers($answers);
    if (checkMap("seed[{$name}]", $got, $expected)) {
        printf("  PASS  %-14s %s\n", $name, json_encode($got));
    }
}

// The weights must never reach the browser — a user who can see that
// "Warm and full" is worth +3 bass can answer strategically.
echo "\nQuestions sent to the browser carry no weights\n";
$leaked = 0;
foreach (quiz_list_questions() as $question) {
    foreach ($question["options"] as $option) {
        if (array_key_exists("impact", $option)) {
            $leaked++;
        }
    }
}
check("options exposing 'impact'", $leaked, 0);
if ($leaked === 0) {
    echo "  PASS  none of the options carry impact weights\n";
}


/* ──────────────────────────── the adaptive test ───────────────────────── */

echo "\nFull ten-question runs\n";

foreach ($golden["runs"] as $run) {
    $label = "{$run['seed']}/{$run['pattern']}";

    $seed = $run["seed"] === "noseed" ? null : quiz_score_answers([
        "genre"=>"hiphop","signature"=>"warm","vocals"=>"forward",
        "harshness"=>"often","punch"=>"often","environment"=>"noisy",
    ]);

    $_SESSION = [];
    $pair = at_start_session($seed);

    $ok = true;
    foreach ($run["answers"] as $i => $answer) {
        $step = $run["steps"][$i];

        // Every pair the user is shown must match, not just the final
        // answer — identical endpoints reached by a different route would
        // mean the two implementations only agree by coincidence.
        $ok = check("{$label} step{$i} question", $pair["question"], $step["question"]) && $ok;
        $ok = check("{$label} step{$i} param", $pair["param"], $step["param"]) && $ok;
        $ok = check("{$label} step{$i} round", $pair["round"], $step["round"]) && $ok;
        $ok = check("{$label} step{$i} sample", $pair["sample"], $step["sample"]) && $ok;
        $ok = checkMap("{$label} step{$i} A", $pair["A"], $step["A"]) && $ok;
        $ok = checkMap("{$label} step{$i} B", $pair["B"], $step["B"]) && $ok;

        $result = at_record_answer($answer);

        if (!empty($result["done"])) {
            $ok = checkMap("{$label} profile", $result["profile"], $run["profile"]) && $ok;
            $ok = check("{$label} confidence", $result["confidence"], $run["confidence"]) && $ok;
            $ok = checkMap("{$label} precision", $result["precision"], $run["precision"]) && $ok;
            $ok = check("{$label} questions used", $i + 1, $run["questions_used"]) && $ok;
            break;
        }

        $pair = $result["next"];
    }

    if ($ok) {
        printf("  PASS  %-20s %s  conf %s\n",
            $label, json_encode($run["profile"]), $run["confidence"]);
    }
}


/* ───────────────────────── behaviour, not just values ─────────────────── */

echo "\nRejects bad input rather than throwing\n";

$_SESSION = [];
check("answer with no session", at_record_answer("A")["error"] ?? null,
      "No active session. Start the test first.");
echo "  PASS  refuses an answer before the test starts\n";

at_start_session(null);
$bad = at_record_answer("C");
check("invalid side", $bad["error"] ?? null, 'preferred must be "A" or "B"');
echo "  PASS  refuses a side that is neither A nor B\n";

// Ten answers is the whole test; an eleventh must not extend it.
$_SESSION = [];
at_start_session(null);
for ($i = 0; $i < 10; $i++) {
    $last = at_record_answer("A");
}
check("test is done after ten", $last["done"] ?? false, true);
$extra = at_record_answer("A");
check("an eleventh answer is refused", $extra["error"] ?? null, "Test already complete");
echo "  PASS  the test ends after exactly ten questions\n";


/* ────────────────────── the profile aggregation layer ─────────────────── */

require_once __DIR__ . "/../api/preference_profile.php";
require_once __DIR__ . "/../api/hearing_preservation.php";

$profileGolden = json_decode(
    file_get_contents(__DIR__ . "/golden_profile.json"), true);

echo "\nWeighting function\n";

foreach ($profileGolden["_weights"] as $case) {
    $got = pp_assessment_weight($case["confidence"], $case["age_days"]);
    $label = sprintf("conf=%s age=%s",
        var_export($case["confidence"], true), var_export($case["age_days"], true));
    if (check("weight {$label}", $got, $case["weight"])) {
        printf("  PASS  %-34s %.12f\n", $label, $got);
    }
}

echo "\nAggregation, analysis and wording\n";

foreach ($profileGolden as $name => $expected) {
    if ($name === "_weights") {
        continue;
    }

    $got = pp_build($expected["input"]);
    $ok = true;

    $ok = checkMap("{$name} target", $got["target"], $expected["target"]) && $ok;
    $ok = checkMap("{$name} spread", $got["spread"], $expected["spread"]) && $ok;
    $ok = check("{$name} count", $got["assessment_count"], $expected["assessment_count"]) && $ok;
    $ok = check("{$name} total_weight", $got["total_weight"], $expected["total_weight"]) && $ok;
    $ok = check("{$name} dominant_share", $got["dominant_share"], $expected["dominant_share"]) && $ok;
    $ok = check("{$name} summary", $got["analysis"]["summary"], $expected["summary"]) && $ok;

    foreach ($expected["regions"] as $i => $region) {
        foreach ($region as $key => $value) {
            $ok = check("{$name} region{$i}.{$key}", $got["regions"][$i][$key], $value) && $ok;
        }
    }

    // The sentences matter as much as the numbers. They are what the user
    // actually reads, and a wrong branch produces confident nonsense.
    foreach ($expected["sentences"] as $i => $sentence) {
        $ok = check("{$name} sentence{$i}", $got["analysis"]["regions"][$i]["sentence"], $sentence) && $ok;
    }

    // Hearing preservation, including which notes fire.
    $hp = hp_build($got);
    $wantHp = $expected["hearing"];
    $ok = check("{$name} hearing note count", count($hp["notes"]), count($wantHp["notes"])) && $ok;
    foreach ($wantHp["notes"] as $i => $note) {
        $ok = check("{$name} hearing note{$i} band", $hp["notes"][$i]["band"], $note["band"]) && $ok;
        $ok = check("{$name} hearing note{$i} body", $hp["notes"][$i]["body"], $note["body"]) && $ok;
    }
    $ok = check("{$name} hearing tips", count($hp["tips"]), count($wantHp["tips"])) && $ok;
    $ok = check("{$name} hearing standard", $hp["standard_note"], $wantHp["standard_note"]) && $ok;
    $ok = check("{$name} hearing disclaimer", $hp["disclaimer"], $wantHp["disclaimer"]) && $ok;

    if ($ok) {
        $levels = [];
        foreach ($got["regions"] as $region) {
            $levels[] = $region["level"];
        }
        printf("  PASS  %-19s %-52s %s\n",
            $name, json_encode($got["target"]), implode("/", $levels));
    }
}

echo "\nThe hearing section cannot change the profile it reads\n";

$before = pp_build($profileGolden["consistent"]["input"]);
$snapshot = json_encode($before);
hp_build($before);
check("profile unchanged after hp_build()", json_encode($before), $snapshot);
echo "  PASS  hp_build() is read-only\n";

echo "\nNo diagnostic language anywhere in the hearing section\n";

$banned = ["hearing loss", "hearing damage", "damaged", "tinnitus", "hyperacusis",
           "diagnos", "symptom", "disorder", "impairment", "deaf"];
$corpus = strtolower(json_encode(hp_build($before)));
$hits = [];
foreach ($banned as $word) {
    if (strpos($corpus, $word) !== false) {
        $hits[] = $word;
    }
}
check("banned phrases", implode(",", $hits), "");
echo "  PASS  none of " . count($banned) . " banned phrases appear\n";


/* ────────────────────── the recommendation engine ─────────────────────── */

require_once __DIR__ . "/../api/recommend.php";

$rec = json_decode(file_get_contents(__DIR__ . "/golden_recommend.json"), true);

echo "\nConstants\n";
check("SCORE_SCALE", REC_SCORE_SCALE, $rec["constants"]["SCORE_SCALE"]);
check("CANDIDATE_POOL_SIZE", REC_CANDIDATE_POOL_SIZE, $rec["constants"]["CANDIDATE_POOL_SIZE"]);
check("RESULTS_SHOWN", REC_RESULTS_SHOWN, $rec["constants"]["RESULTS_SHOWN"]);
check("MEASUREMENT_DECIMALS", REC_MEASUREMENT_DECIMALS, $rec["constants"]["MEASUREMENT_DECIMALS"]);
echo "  PASS  all four match the Python\n";

echo "\nMedian\n";
foreach (["odd" => [3,1,2], "even" => [4,1,3,2], "empty" => [],
          "one" => [7.5], "negs" => [-3,-1,-2,-4]] as $name => $values) {
    if (check("median {$name}", rec_median($values), $rec["medians"][$name])) {
        printf("  PASS  %-6s %s -> %s\n", $name, json_encode($values), json_encode(rec_median($values)));
    }
}

echo "\nCatalogue filtering and baseline\n";

$scorable = [];
foreach ($rec["catalogue"] as $iem) {
    if (rec_has_complete_measurement($iem)) {
        $scorable[] = $iem;
    }
}
$gotIds = array_map(fn($i) => $i["id"], $scorable);
check("incomplete entries dropped", $gotIds, $rec["scorable_ids"]);
printf("  PASS  %d of %d kept (the one missing a band is dropped)\n",
    count($scorable), count($rec["catalogue"]));

$baseline = rec_catalog_baseline($scorable);
checkMap("baseline", $baseline, $rec["baseline"]);
printf("  PASS  medians %s\n", json_encode($baseline));

echo "\nScoring and ranking\n";

foreach ($rec["runs"] as $pname => $run) {
    $ok = true;

    $scored = [];
    foreach ($scorable as $iem) {
        $scored[] = rec_score_iem($iem, $run["profile"], $baseline);
    }

    // Every earphone's centred gains, per-band match and overall score.
    foreach ($run["scored"] as $i => $want) {
        $got = $scored[$i];
        $ok = check("{$pname} #{$want['iem_id']} id", $got["iem_id"], $want["iem_id"]) && $ok;
        $ok = checkMap("{$pname} #{$want['iem_id']} gains", $got["gains"], $want["gains"]) && $ok;
        $ok = checkMap("{$pname} #{$want['iem_id']} band_match", $got["band_match"], $want["band_match"]) && $ok;
        $ok = check("{$pname} #{$want['iem_id']} match_score", $got["match_score"], $want["match_score"]) && $ok;
    }

    // The ranking itself, in order. Ties and the null price are in the
    // fixture on purpose — those are where two stable sorts can silently
    // disagree.
    $ranked = rec_rank_recommendations($scored);
    $ok = check("{$pname} ranked ids", array_map(fn($r) => $r["iem_id"], $ranked),
                $run["ranked_ids"]) && $ok;
    $ok = check("{$pname} ranked prices", array_map(fn($r) => $r["price"], $ranked),
                $run["ranked_prices"]) && $ok;

    if ($ok) {
        printf("  PASS  %-8s top5 %s\n", $pname, json_encode($run["ranked_ids"]));
    }
}

echo "\nThe two-stage sort actually does something\n";
// If ranking were by match alone the results would be a different set;
// this asserts the price stage is really being applied.
$scored = [];
foreach ($scorable as $iem) {
    $scored[] = rec_score_iem($iem, $rec["runs"]["neutral"]["profile"], $baseline);
}
$byMatchOnly = $scored;
usort($byMatchOnly, fn($a, $b) => $b["match_score"] <=> $a["match_score"]);
$matchTop5 = array_map(fn($r) => $r["iem_id"], array_slice($byMatchOnly, 0, 5));
$actual = $rec["runs"]["neutral"]["ranked_ids"];
check("price stage changes the result", $matchTop5 === $actual, false);
printf("  PASS  match-only would give %s, two-stage gives %s\n",
    json_encode($matchTop5), json_encode($actual));


/* ─────────────────────────────────── result ───────────────────────────── */

echo "\n";
printf("%d checks, %d failures\n\n", $checks, $failures);

if ($failures === 0) {
    echo "The PHP produces exactly what the Python produced.\n";
    echo "Safe to retire backend/ for the parts covered here.\n\n";
    exit(0);
}

echo "The port does NOT match. Do not deploy this — a profile that differs\n";
echo "from the original recommends different earphones, silently.\n\n";
exit(1);
